FS-641 funding service design fund discovery
communitiesuk/funding-service-design-fund-discovery-frontend pull request #1
Opened 2022-03-07 17:07 UTC by ramsharma-prog

2022-03-07 17:20 UTC, stevewalton28 requested changes

2022-03-07 17:20 UTC, stevewalton28 commented on .dockerignore
> +app/static
new line at end of file needed

2022-03-07 17:20 UTC, stevewalton28 commented on .flaskenv
> +FLASK_RUN_PORT=5000
new line at end of file needed

2022-03-07 17:20 UTC, stevewalton28 commented on .gitignore
> +app/static
new line at end of file needed

2022-03-07 17:20 UTC, stevewalton28 commented on app.py
> +import app #noqa
new line at end of file needed

2022-03-07 17:20 UTC, stevewalton28 commented on app/__init__.py
> +from app.create_app import app  # noqa
new line at end of file needed

2022-03-07 17:20 UTC, stevewalton28 commented on app/create_app.py
> +app = create_app()
new line at end of file needed

2022-03-07 17:20 UTC, stevewalton28 commented on app/default/routes.py
> +    return render_template("500.html"), 500
new line at end of file needed

2022-03-07 17:20 UTC, stevewalton28 commented on app/discovery/forms.py
> +    search = StringField('Search fund', validators=[DataRequired()])
new line at end of file needed

2022-03-07 17:20 UTC, stevewalton28 commented on app/discovery/routes.py
> +    return rounds
new line at end of file needed

2022-03-07 17:20 UTC, stevewalton28 commented on app/discovery/templates/fund.html
> +  {% endblock %}
new line at end of file needed

2022-03-07 17:20 UTC, stevewalton28 commented on app/discovery/templates/search.html
> +  {% endblock %}
new line at end of file needed

2022-03-07 17:20 UTC, stevewalton28 commented on app/templates/500.html
> +{% endblock %}
new line at end of file needed

2022-03-07 17:20 UTC, stevewalton28 commented on app/templates/base.html
> +{% endblock %}
new line at end of file needed

2022-03-07 17:20 UTC, stevewalton28 commented on app/templates/footer.html
> +  }) }}
new line at end of file needed

2022-03-07 17:20 UTC, stevewalton28 commented on build.py
> +    build_assets()
new line at end of file needed

2022-03-07 17:20 UTC, stevewalton28 commented on dockerfile
> +CMD ["flask", "run", "--host=0.0.0.0"]
new line at end of file needed

2022-03-07 17:20 UTC, stevewalton28 commented on manifest.yml
> +  command: flask run --host 0.0.0.0 --port 8080
new line at end of file needed

2022-03-07 17:20 UTC, stevewalton28 commented on tests/test_round_store.py
> +    assert rounds== expected_contents
new line at end of file needed

2022-03-07 17:30 UTC, ramsharma-prog commented on .dockerignore
> +app/static
New line 135 added

2022-03-07 17:31 UTC, ramsharma-prog commented on .gitignore
> +app/static
New line 133 added

2022-03-07 17:39 UTC, ramsharma-prog commented on .flaskenv
> +FLASK_RUN_PORT=5000
New line 4 added at the end

2022-03-07 17:41 UTC, ramsharma-prog commented on app/templates/footer.html
> +  }) }}
New  line 43 added at the end

2022-03-07 17:42 UTC, ramsharma-prog commented on build.py
> +    build_assets()
New  line 61 added at the end

2022-03-07 17:43 UTC, ramsharma-prog commented on dockerfile
> +CMD ["flask", "run", "--host=0.0.0.0"]
New  line 13 added at the end

2022-03-07 17:43 UTC, ramsharma-prog commented on manifest.yml
> +  command: flask run --host 0.0.0.0 --port 8080
New  line 17 added at the end

2022-03-07 17:44 UTC, ramsharma-prog commented on tests/test_round_store.py
> +    assert rounds== expected_contents
New  line 58  added at the end

2022-03-07 17:49 UTC, ramsharma-prog commented on app/create_app.py
> +app = create_app()
New  line 87  added at the end

2022-03-07 17:50 UTC, ramsharma-prog commented on app/default/routes.py
> +    return render_template("500.html"), 500
New  line 15 added at the end

2022-03-07 17:50 UTC, ramsharma-prog commented on app/discovery/forms.py
> +    search = StringField('Search fund', validators=[DataRequired()])
New  line 7  added at the end

2022-03-07 17:51 UTC, ramsharma-prog commented on app/discovery/routes.py
> +    return rounds
New  line 42 added at the end

2022-03-07 17:52 UTC, ramsharma-prog commented on app/discovery/templates/fund.html
> +  {% endblock %}
New  line 61 added at the end

2022-03-07 17:53 UTC, ramsharma-prog commented on app/discovery/templates/search.html
> +  {% endblock %}
New  line 55 added at the end

2022-03-07 17:54 UTC, ramsharma-prog commented on app/templates/500.html
> +{% endblock %}
New  line 13 added at the end

2022-03-07 17:54 UTC, ramsharma-prog commented on app/templates/base.html
> +{% endblock %}
New  line 25 added at the end

2022-03-08 19:38 UTC, harryyo requested changes
Great progress Ram! Added notes for things that could be modified perhaps

2022-03-08 19:38 UTC, harryyo commented on app/discovery/routes.py
> +        fund_results = model.query_fund(query, FUND_SEARCH_ENDPOINT)
It might be worth considering refactoring this to put the query_fund() function in app/discovery/data.py along with the rounds_search() as they're both operations that involve getting data from external api endpoints. You could then also define the endpoints there too so all the interactions and settings for external api data calls are in the same file (to make it easier to update in the future)

2022-03-08 19:38 UTC, harryyo commented on app/discovery/routes.py
> +    rounds = rounds_search(f"{ROUND_SEARCH_ENDPOINT}/{id}")
Might be cleaner to have the rounds_search() function just take a `fund_id: str` and then you do the string formatting in the function itself in app/discovery/data.py (so all that stuff is in the same place, and you can validate the fund_id separately from the endpoint)

2022-03-08 19:38 UTC, harryyo commented on app/discovery/routes.py
> +def search_form():
Perhaps this could be called search_funds() as this route is not just a form as it returns results as well? Calling it search_form makes it a bit confusing (to me at least on first look) as to whether it actually just returns a form instance or something like that - it actually does much more!

2022-03-08 19:38 UTC, harryyo commented on app/discovery/data.py
> +                print(fund_rounds)
Print() here should prob be removed ?

2022-03-08 19:38 UTC, harryyo commented on app/discovery/data.py
> +                rounds_data.format_deadline(rounds_data.deadline)
These two lines could be done automatically on the model if you want them every time using something like the @property decorator on an opens_display() and deadline_display() method for example (see note on model). So you wouldn't need these lines here

2022-03-08 19:38 UTC, harryyo commented on app/config.py
> +
This could be a good place to put the FUND_STORE_API_HOST and ROUND_STORE_API_HOST variables and get them from environment variables

2022-03-08 19:38 UTC, harryyo commented on app/discovery/models/model.py
> +    def format_opens(self, start):
You could add the [@property](https://www.programiz.com/python-programming/property) decorator to these two methods and then you could use {{ round.format_opens }} and use self.opens in place of passing "start" to this function

2022-03-09 09:27 UTC, ramsharma-prog commented on README.md
> +
Thanks Harry, updated

2022-03-09 09:32 UTC, ramsharma-prog commented on app/discovery/models/model.py
> +in for data processing & data alteration
I agree, I removed the model & renamed it however name round is used in the app so to avoid confusion renamed it to RoundStore

2022-03-09 09:33 UTC, ramsharma-prog commented on app/discovery/models/model.py
> +    """
I agree, I removed the model & renamed it however name round is used in the app so to avoid confusion renamed it to RoundStore

2022-03-09 09:36 UTC, ramsharma-prog commented on app/discovery/models/model.py
> +    DATA from round store funds runs through the model
Thanks, Harry, agree! Updated docstring

2022-03-09 09:41 UTC, ramsharma-prog commented on app/discovery/routes.py
> +def search_form():
Yes, that would make more sense. Renamed it!

2022-03-09 09:42 UTC, ramsharma-prog commented on app/discovery/data.py
> +                print(fund_rounds)
Yes, already done!

2022-03-09 09:44 UTC, ramsharma-prog commented on app/discovery/data.py
> +                rounds_data.format_deadline(rounds_data.deadline)
Ah ok, I will have a look. Thanks for the suggestion

2022-03-09 09:46 UTC, ramsharma-prog commented on app/discovery/models/model.py
> +    def format_opens(self, start):
Thank you for the suggestion! I will definately  look into it

2022-03-09 14:58 UTC, ramsharma-prog commented on manifest.yml
> +- name: funding-service-design-assessment-dev
Thanks, Harry! it was supposed to be  funding-service-design-fund-discovery-frontend-dev

2022-03-09 15:11 UTC, ramsharma-prog commented on app/discovery/models/_endpoints.py
> +"""
Yes,  _ is the reference to make sure endpoints are not changed for time being. Although I will be refactoring this file as suggested hostnames

2022-03-09 15:12 UTC, ramsharma-prog commented on app/discovery/models/_endpoints.py
> +"""
Yes, _ is for reference to make sure endpoints are not changed for time being

2022-03-09 15:29 UTC, ramsharma-prog commented on app/discovery/templates/fund.html
> +    {{ rounds_data.fund_id|upper}} </label> </h1>
I am working on it

2022-03-09 15:30 UTC, ramsharma-prog commented on tests/test_fund_store.py
> +    response = requests.get(TEST_FUND_SEARCH_ENDPOINT_RESPONSE)
Yes, I am aware of the hardcode endpoints & I will be working on it as suggested!

2022-03-09 15:31 UTC, ramsharma-prog commented on tests/test_fund_store.py
> +    assert funds == expected_contents
Yes, I am working on this today

2022-03-09 15:35 UTC, ramsharma-prog commented on tests/test_round_store.py
> +    assert rounds== expected_contents
working on it

2022-03-09 15:35 UTC, ramsharma-prog commented on tests/test_round_store.py
> +    assert response.status_code == 200
Thanks Harry, working on it

2022-03-09 15:36 UTC, ramsharma-prog commented on tests/accessability_test_report.json
> +{
Okay, thanks for letting me know

2022-03-09 15:54 UTC, ramsharma-prog commented on app/discovery/routes.py
> +        fund_results = model.query_fund(query, FUND_SEARCH_ENDPOINT)
Yes, agree! query_fund moved to data.py

2022-03-09 15:55 UTC, ramsharma-prog commented on app/config.py
> +
Yes, working on it

2022-03-13 18:37 UTC, ramsharma-prog commented on tests/test_fund_store.py
> +    response = requests.get(TEST_FUND_SEARCH_ENDPOINT_RESPONSE)
This test has been removed since Jack is running a test on fund store

2022-03-13 18:38 UTC, ramsharma-prog commented on tests/test_fund_store.py
> +    assert funds == expected_contents
This test has been removed since Jack is running a test on fund store

2022-03-13 18:38 UTC, ramsharma-prog commented on tests/test_round_store.py
> +    assert response.status_code == 200
This test has been removed since Harry is running a test on round  store

2022-03-13 18:39 UTC, ramsharma-prog commented on app/discovery/routes.py
> +    rounds = rounds_search(f"{ROUND_SEARCH_ENDPOINT}/{id}")
This test has been removed since Harry is running a test on  fund rounds

2022-03-13 18:40 UTC, ramsharma-prog commented on tests/test_round_store.py
> +    assert rounds== expected_contents
This test has been removed since Harry  is running a test on fund round store

2022-03-13 18:41 UTC, ramsharma-prog commented on app/config.py
> +
Endpoints added to the config.py

2022-03-13 19:42 UTC, ramsharma-prog commented on app/discovery/templates/fund.html
> +    {{ rounds_data.fund_id|upper}} </label> </h1>
Hi Harry, wouldn't it be easier if the fund name was added to the fund store database so it makes it simple & easier for me to display the fund name? 😄

2022-03-15 08:31 UTC, ramsharma-prog commented on app/discovery/templates/fund.html
> +    {{ rounds_data.fund_id|upper}} </label> </h1>
Functionality added

2022-03-15 09:29 UTC, stevewalton28 approved these changes

2022-03-15 16:43 UTC, SentientHousePlant requested changes
Very nice Ram! Just some small things to address :) 💯

2022-03-15 16:43 UTC, SentientHousePlant commented on .vscode/settings.json
> +{
this should be in gitignore

2022-03-15 16:43 UTC, SentientHousePlant commented on .gitignore
This is very slim. See Gitignore.io to create a more comprehensive gitignore.

2022-03-15 16:43 UTC, SentientHousePlant commented on .gitignore
or use the one from another repo

2022-03-15 16:43 UTC, SentientHousePlant commented on app/discovery/data.py
> +    """
Nice docstrings - look at a docstring generator plug in to ensure they contain a summary, arg description, and return description.

2022-03-15 16:43 UTC, SentientHousePlant commented on app/discovery/routes.py
> +"""
Don't use """ for code comments please :) you can use #

2022-03-15 16:43 UTC, SentientHousePlant commented on pyproject.toml
> +description = "The funding service design frontend for the DLUHC."
Consider changing the description to be more descriptive.

2022-03-15 16:43 UTC, SentientHousePlant commented on tests/test_accessibility.py
> +
fix newlines.

2022-03-15 16:46 UTC, SentientHousePlant requested changes

2022-03-15 16:46 UTC, SentientHousePlant commented on app/config.py
> +ROUND_STORE_API_HOST="https://funding-service-design-round-store-dev.london.cloudapps.digital"
These are hardcoded - have it so that if an environment variable isn't set then it defaults to theses or something else.

2022-03-15 16:50 UTC, ramsharma-prog commented on .gitignore
I copied from yours lol

2022-03-15 16:51 UTC, ramsharma-prog commented on .gitignore
I copied yours :)

2022-03-15 16:53 UTC, ramsharma-prog commented on app/default/routes.py
> +from flask import Blueprint
That would make more sense :)
Done

2022-03-15 21:15 UTC, ramsharma-prog commented on app/discovery/models/rounds.py
> +    """
Thanks, Jack. I have downloaded the autoDocstring removed comment from the top. Also read through the link :)

2022-03-15 21:18 UTC, ramsharma-prog commented on app/discovery/models/rounds.py
> +        return "{:,}".format(self.eligibility_criteria['max_project_cost'])
Below actions taken :) Thank you!

This repo comes with a .pre-commit-config.yaml, if you wish to use this do
the following while in your virtual enviroment:

    pip install pre-commit black

    pre-commit install

Once the above is done you will have autoformatting and pep8 compliance built
into your workflow. You will be notified of any pep8 errors during commits.

2022-03-15 21:19 UTC, ramsharma-prog commented on app/discovery/routes.py
> +"""
Thanks, triple quotes removed & the global variable query has been removed

2022-03-15 22:01 UTC, ramsharma-prog commented on app/discovery/routes.py
> +        message = "No rounds exist for this fund"
Thanks, Jack, I will look into it.
I am using the message variable in jinja to display the error. Although I changed the variable name to error :).

2022-03-15 22:37 UTC, ramsharma-prog commented on app/discovery/templates/search.html
> +        {{ govukInput({
it's inside the input field however I tried playing around with it either we get a permanent error message displaying or none. I will have a fresh look again

2022-03-15 22:39 UTC, ramsharma-prog commented on pyproject.toml
> +description = "The funding service design frontend for the DLUHC."
description = "The funding service design frontend for discovery fund for DLUHC."

2022-03-15 22:40 UTC, ramsharma-prog commented on tests/test_accessibility.py
> +
Done :)

2022-03-15 22:45 UTC, ramsharma-prog commented on app/discovery/models/model.py
> +in for data processing & data alteration
Name changed to rounds.py

2022-03-15 22:45 UTC, ramsharma-prog commented on app/discovery/models/model.py
> +    """
Name changed to Rounds

2022-03-15 22:46 UTC, ramsharma-prog commented on app/discovery/models/_endpoints.py
> +"""
_endoint file removed

2022-03-15 22:50 UTC, ramsharma-prog commented on app/discovery/data.py
> +    """
Downloaded plugin. Thank you!

2022-03-16 17:17 UTC, ramsharma-prog commented on app/discovery/templates/search.html
> +        {{ govukInput({
I couldn't find a way to add an error message to the button. Happy to have a chat :)

2022-03-16 17:20 UTC, ramsharma-prog commented on app/config.py
> +ROUND_STORE_API_HOST="https://funding-service-design-round-store-dev.london.cloudapps.digital"
I am going to need some time to create a database, rewrite the functions so it can perform the search locally and to the endpoints :)

2022-03-16 17:22 UTC, ramsharma-prog commented on .vscode/settings.json
> +}
Sure, thanks for letting me know :)

2022-03-16 17:23 UTC, ramsharma-prog commented on README.md
> +Place brief descriptions of Pipelines here
Thank you!

2022-03-16 17:24 UTC, ramsharma-prog commented on app/config.py
> +def get_endpoints():
Function name has been changed. Thanks for educating Harry!

2022-03-16 17:25 UTC, ramsharma-prog commented on app/discovery/models/rounds.py
> +"""
It was just to avoid the confusion with python method round :)

2022-03-16 17:36 UTC, harryyo approved these changes

2022-03-16 20:53 UTC, ramsharma-prog commented on app/discovery/templates/search.html
> +      {% for error in form.search.errors %}
This messes up the layout. Defo will fund a better way of doing it in future. Thank you :)

2022-03-16 20:56 UTC, ramsharma-prog commented on app/discovery/routes.py
> +                fund_details.append(rounds_data)
Thanks, Harry, function added.  Although I am sure that you will have some suggestions on naming conventions? :)

def list_data(lst_data,data_func):
    data = []
    for lst in lst_data:
        data.append(data_func(lst))
    return data

2022-03-16 20:58 UTC, ramsharma-prog commented on app/discovery/data.py
> +def query_fund_rounds(fund_rounds):
Thanks, Harry, function renamed to get_data as suggested :)

2022-03-16 20:59 UTC, ramsharma-prog commented on app/discovery/data.py
> +    store_rounds_data = RoundStore(
Function moved to Rounds class as static function as suggested. That was very helpful! Thank you!

2022-03-16 21:03 UTC, ramsharma-prog commented on app/discovery/templates/search.html
> +{% block content %}
I tried, somehow it doesn't work for me. Although I would love to have some help :)

2022-03-16 21:05 UTC, ramsharma-prog commented on pytest.ini
> +[pytest]
The accessibility test runs once deployed hence it has been marked. I do understand that I need have a better approach with accessibility testing tho :) Work/learning in progress :)

2022-03-16 21:14 UTC, ramsharma-prog commented on app/discovery/routes.py
> +    """
Renamed it to funds & Query global variable removed. Again Thank you for educating me.

2022-03-16 21:21 UTC, ramsharma-prog commented on app/discovery/routes.py
> +                            fund_results = fund_results
Renamed :)

 return render_template(
        "fund.html",
        fund = fund,
       rounds = rounds
    )

2022-03-16 21:23 UTC, ramsharma-prog commented on app/discovery/routes.py
> +    fund_results = query_fund(
The function has been renamed to get_data as it is used for funds & rounds

2022-03-16 21:25 UTC, ramsharma-prog commented on app/discovery/templates/search.html
> +{% block content %}
I tried somehow I am having an error displaying from afterward. Probably need some help? :)

2022-03-16 21:29 UTC, ramsharma-prog commented on tests/test_accessibility.py
> +@pytest.mark.usefixtures("selenium_chrome_driver")
Thank you! 
Created fixture(session) & added live_server

2022-03-16 21:32 UTC, ramsharma-prog commented on tests/test_data_response.py
> +from urllib.request import urlopen
I did have the test at the beginning which was tested against the expected contents from rounds & funds store but after discussion with Jack, I realised that the data is being tested by you & Jack so I should probably test my search page response.  As I mentioned earlier I do need to get a lot better at testing. Work & learning in progress :)

2022-03-16 21:36 UTC, ramsharma-prog commented on app/config.py
> +ROUND_STORE_API_HOST="https://funding-service-design-round-store-dev.london.cloudapps.digital"
Happy to have a discussion as it will simplify the tests as well :)

2022-03-17 09:21 UTC, SentientHousePlant approved these changes
Nice!

2022-03-18 11:46 UTC, SentientHousePlant requested changes
Great work Ram. 

I really like the use of json in order to mock data - I think this makes it very clear what data is being mocked. The functions you wrote can be used by the rest of the team too! Consider writing a small python package which allows people to use json as a mock url.

The content tests are very concise and test that rounds work.

I really like the use of url args in order to avoid complicated posting and selenium tests - this also means that users can share search results - great work!

Really good Ram!

2022-03-18 11:46 UTC, SentientHousePlant commented on app/default/error_routes.py
> +@default_bp.errorhandler(404)
Test error route :)

2022-03-18 11:46 UTC, SentientHousePlant commented on app/discovery/models/data.py
> +    """Function takes get request to
Great docstrings :)

2022-03-18 11:57 UTC, SentientHousePlant approved these changes

2022-03-18 11:57 UTC, ramsharma-prog commented on app/discovery/models/data.py
> +    """Function takes get request to
:smile:

2022-03-18 11:58 UTC, ramsharma-prog commented on app/default/error_routes.py
> +@default_bp.errorhandler(404)
Thank you for your support, Jack. Test added

2022-03-18 12:17 UTC, merged