FS 710 rounds endpoint renaming
communitiesuk/funding-service-design-fund-discovery-frontend pull request #2
Opened 2022-04-20 15:48 UTC by ramsharma-prog

2022-04-21 13:26 UTC, ramsharma-prog commented on app/config.py
>  FUND_SEARCH_ENDPOINT = "search"
FUNDS_URL refactored.

2022-04-21 13:27 UTC, ramsharma-prog commented on app/discovery/models/data.py
> +            print(f"NONE QUERY: {query}")
print statement removed

2022-04-21 13:30 UTC, ramsharma-prog commented on app/discovery/models/data.py
> +        #     return data.get(endpoint)
commented out return of all funds locally for now as the fund store does not return all funds with just empty string however return all funds with empty string with white space in between.

2022-04-26 08:24 UTC, harryyo commented on app/discovery/models/data.py
> +    """GIVEN function return query from
Remove given here (doesn't make sense) just description of what the function does is fine

2022-04-26 08:48 UTC, SentientHousePlant requested changes

2022-04-26 08:48 UTC, SentientHousePlant commented on tests/test_data_response.py
> +    assert b"blloobllaalive" not in response.data
🔧 🤔 What does this test check for? Looks like it checks if the word **blloobllaalive** isn't in the page when we search for **fund**...but the test is called search page not found?

2022-04-26 09:36 UTC, harryyo reviewed
Hi Ram, A few comments, mainly to remove the GIVEN syntax where not needed and just use it in tests to describe expected state before the test runs. I think the data.py needs a slight refactor just so that the local/remote logic doesn't have to be duplicated - do gimme a bell if comments not clear...!

2022-04-26 09:36 UTC, harryyo commented on app/discovery/models/data.py
> +    """GIVEN function return query from
Remove Given here, just describe what the function does

2022-04-26 09:36 UTC, harryyo commented on app/discovery/models/data.py
> +    """GIVEN function return None data to
Remove GIVEN here, just describe what the function does

2022-04-26 09:36 UTC, harryyo commented on app/discovery/models/data.py
> +    """GIVEN function takes get request to
Remove GIVEN and describe

2022-04-26 09:36 UTC, harryyo commented on app/discovery/models/data.py
> +def get_local_fund(query, endpoint):
What's the reason for having a get_local_fund function? get_fund should perform the same whether the data comes from a remote or local endpoint. Break this out into a get_data and get_local data so that you don't have to replicate the endpoint.startswith("https://") logic

2022-04-26 09:36 UTC, harryyo commented on app/discovery/models/data.py
> +    """GIVEN function loops through json data &
No need for this change the previous version is clear I would say!

2022-04-26 09:36 UTC, harryyo commented on app/discovery/routes.py
> +    """GIVEN route takes a search form, retrieves
Remove GIVEN

2022-04-26 09:36 UTC, harryyo commented on app/discovery/routes.py
>      GIVEN Function calls the RoundStore function
Remove GIVEN

2022-04-26 09:36 UTC, harryyo commented on tests/test_data_response.py
> +    assert b"blloobllaalive" not in response.data
Better to check if something you expect does exist rather than something random doesn't?

2022-04-26 09:36 UTC, harryyo commented on app/discovery/models/data.py
> +    if "https://" in endpoint:
However, this function shouldn't really require different logic if the endpoint is local. The query_fund logic should really work regardless of where the data is

2022-04-26 13:07 UTC, ramsharma-prog commented on app/discovery/models/data.py
> +    """GIVEN function return query from
Removed

2022-04-26 13:09 UTC, ramsharma-prog commented on tests/test_data_response.py
> +    assert b"blloobllaalive" not in response.data
This was removed. I haven't pushed the changes.  There was a bug so I had to remove fund & put random word but fixed later on

2022-04-26 13:14 UTC, ramsharma-prog commented on app/discovery/models/data.py
> +    if "https://" in endpoint:
if endpoint.startswith("https://"): UPDATED.

it requires HTTPS check as this function makes a call to the fund store which is slightly different from the local function?

2022-04-26 13:14 UTC, ramsharma-prog commented on app/discovery/models/data.py
> +    """GIVEN function relates with query_local_fund
removed

2022-04-26 13:14 UTC, ramsharma-prog commented on app/discovery/models/data.py
> +    """GIVEN function return query from
REMOVED

2022-04-26 13:14 UTC, ramsharma-prog commented on app/discovery/models/data.py
> +    """GIVEN function takes get request to
REMOVED

2022-04-26 13:18 UTC, ramsharma-prog commented on app/discovery/models/data.py
> +def get_local_fund(query, endpoint):
get_local_fund function is a part of qyery_local_fund function. Although can cut down codes. Will work on it later in the week.

2022-04-26 13:18 UTC, ramsharma-prog commented on app/discovery/models/data.py
> +    """GIVEN function loops through json data &
removed

2022-04-26 13:18 UTC, ramsharma-prog commented on app/discovery/routes.py
>      GIVEN Function calls the RoundStore function
REMOVED

2022-04-26 13:19 UTC, ramsharma-prog commented on app/discovery/routes.py
> +    """GIVEN route takes a search form, retrieves
REMOVED

2022-04-26 13:25 UTC, ramsharma-prog commented on app/discovery/models/data.py
> +    """GIVEN function return None data to
REMOVED

2022-04-27 10:19 UTC, merged