FS 890 891 redirect email to authenticator
communitiesuk/funding-service-design-fund-discovery-frontend pull request #7
Opened 2022-05-14 11:30 UTC by ramsharma-prog

2022-05-17 07:37 UTC, endamccormack commented on app/discovery/models/data.py
> +        # else:
I assume this is not meant to be here

2022-05-17 07:38 UTC, endamccormack commented on manifest.yml
>      ACCOUNT_STORE_API_HOST: https://funding-service-design-account-store-dev.london.cloudapps.digital
is this needed since we got rid of its host elsewhere?

2022-05-17 07:39 UTC, endamccormack commented on tests/conftest.py
> +
My preference would be remove this

2022-05-17 07:40 UTC, endamccormack commented on tests/test_data_response.py
> -
single line between methods

2022-05-17 07:41 UTC, endamccormack commented on tests/test_data_response.py
> +
can you verify this is write for our coding standard? Given there is no class.

2022-05-17 07:42 UTC, endamccormack commented on app/discovery/routes.py
>      if response.status_code == 200:
it is possible this method wont return

2022-05-17 07:44 UTC, endamccormack requested changes
see comments

2022-05-17 07:53 UTC, ramsharma-prog commented on app/discovery/models/data.py
> +        # else:
Yeah, I just commented it out for now as the idea was if the search button was clicked without providing any search keyword, it should grab all the funds from the fund store but Zap doesn't like that hence commented it out in case we might have a way around it later on ? Don't mind removing it tho?

2022-05-17 09:43 UTC, ramsharma-prog commented on tests/conftest.py
> +
Yes, removed. Thanks 😄

2022-05-17 09:44 UTC, ramsharma-prog commented on tests/test_data_response.py
> +
we run the pre-commit hook so black adds two white spaces by default between each block/function

2022-05-17 09:45 UTC, ramsharma-prog commented on tests/test_data_response.py
> -
Same as above. We run the pre-commit hook so black adds two white spaces by default between each block/function

2022-05-17 09:56 UTC, ramsharma-prog commented on app/discovery/routes.py
>      if response.status_code == 200:
I guess no. If the fund has no rounds, it will return ("No rounds exist for this fund"). If there is an active round in the application then only it will have a start application button and that button will redirect it to the authenticator with fund_id & round_id else if there is an unexpected issue, will be redirected to 404. 
However, as soon as Harry has integrated the authenticator with the accounts store to create a magic link, will test it out & see if there is anything we are missing out?

2022-05-17 12:23 UTC, gidsg commented on app/discovery/routes.py
> +    print(response.url)
can we remove this print statement? Guess this is just for debugging?

2022-05-17 13:51 UTC, ramsharma-prog commented on app/discovery/routes.py
> +    print(response.url)
Sorry!! removed

2022-05-18 09:45 UTC, harryyo commented on app/config.py
> +TEST_AUTHENTICATOR_API_HOST = "http://localhost:6794"
the authenticator host doesn't use 6794 (or any particular port yet). You can just put authenticator_host here

2022-05-18 09:45 UTC, harryyo commented on app/config.py
> +    or os.environ.get("TEST_AUTHENTICATOR_STORE_API_HOST")
Is there a reason for not keeping the same pattern as above? There's probably no need to set multiple different over-riding env variables

2022-05-18 09:45 UTC, harryyo commented on app/discovery/models/data.py
> +        # else:
Yep remove. If the search button is clicked without a query the form shouldn't submit (it should require an input)

2022-05-18 09:45 UTC, harryyo commented on app/config.py
> +AUTHENTICATOR_STORE_API_HOST = (
This is not a store - should just be AUTHENTICATOR_API_HOST or AUTHENTICATOR_HOST  even better maybe

2022-05-18 09:45 UTC, harryyo commented on app/config.py
> +AUTHENTICATOR_STORE_API_HOST = (
Also add a MAGIC_LINK_ENDPOINT="/service/magic-links/new?fund_id={fund_id}&round_id={round_id}"

2022-05-18 09:45 UTC, harryyo commented on app/discovery/routes.py
>      return render_template("fund.html", fund=fund, rounds=rounds)
You could just add `authenticator_magic_link_url=AUTHENTICATOR_HOST + MAGIC_LINK_ENDPOINT` and then use that to format urls for the start application buttons in the template

2022-05-18 09:45 UTC, harryyo commented on app/discovery/routes.py
> +@discovery_bp.route("/<fund_id>/<round_id>", methods=["GET", "POST"])
I don't think this route is really necessary, you could just have links in the template for the rounds page that just go straight to the authenticator no?

2022-05-18 09:45 UTC, harryyo commented on app/discovery/templates/fund.html
> +  <a href="{{url_for('discovery_bp.redirect_to_authenticator', fund_id=fund['fund_id'], round_id=round['round_id']) }}" role="button" draggable="false" class="govuk-button govuk-button--start" data-m
this href could just be something like `href="{{authenticator_magic_link_url.format(fund_id=fund_id,round_id=round_id)}}"` maybe?

2022-05-18 09:45 UTC, harryyo commented on manifest.yml
>    env:
Is there a test version of this manifest block (i.e. copy of lines 3-17 but with `-dev` replaced with `-test` for the test govcloud environment?

2022-05-18 09:45 UTC, harryyo commented on tests/test_data_response.py
> -
Two lines between functions single lines between methods of classes I believe

2022-05-18 10:09 UTC, ramsharma-prog commented on app/config.py
> +TEST_AUTHENTICATOR_API_HOST = "http://localhost:6794"
Yes, it doesn't, I am fetching the authenticator from the local environment. Updated to "authenticator_host" tho

2022-05-18 10:18 UTC, ramsharma-prog commented on app/discovery/models/data.py
> +        # else:
removed

2022-05-18 11:07 UTC, ramsharma-prog commented on app/discovery/templates/fund.html
> +  <a href="{{url_for('discovery_bp.redirect_to_authenticator', fund_id=fund['fund_id'], round_id=round['round_id']) }}" role="button" draggable="false" class="govuk-button govuk-button--start" data-m
Made some changes, please review it again

2022-05-18 11:07 UTC, ramsharma-prog commented on app/discovery/routes.py
> +@discovery_bp.route("/<fund_id>/<round_id>", methods=["GET", "POST"])
Made some changes, please review it again

2022-05-18 11:07 UTC, ramsharma-prog commented on app/discovery/routes.py
>      return render_template("fund.html", fund=fund, rounds=rounds)
Made some changes, please review it again

2022-05-18 11:08 UTC, ramsharma-prog commented on app/config.py
> +    or os.environ.get("TEST_AUTHENTICATOR_STORE_API_HOST")
Thanks for pointing that out. Made some changes, please review it again

2022-05-18 11:08 UTC, ramsharma-prog commented on app/config.py
> +AUTHENTICATOR_STORE_API_HOST = (
Done! Made some changes, please review it again 😄

2022-05-18 11:39 UTC, ramsharma-prog commented on tests/test_data_response.py
> -
Yeah the lines between method was fixed 🤔

2022-05-18 11:40 UTC, ramsharma-prog commented on manifest.yml
>    env:
test version added to the manifest

2022-05-18 11:40 UTC, ramsharma-prog commented on manifest.yml
>    env:
🤔

2022-05-18 11:41 UTC, ramsharma-prog commented on app/config.py
> +print(authenticator_magic_link_url)
I have removed it already 😄

2022-05-18 11:58 UTC, gidsg commented on app/config.py
> +print(authenticator_magic_link_url)
Looks like this got back in, so I guess you need to remove it again!

2022-05-18 12:20 UTC, harryyo requested changes

2022-05-18 12:20 UTC, harryyo commented on app/config.py
> +    os.environ.get("AUTHENTICATOR_STORE_API_HOST")
This also needs to be updated to AUTHENTICATOR_API_HOST - also the manifest.yml needs to match for consistency

2022-05-18 12:20 UTC, harryyo commented on app/config.py
> +print(authenticator_magic_link_url)
If authenticator_magic_link_url is set here (rather than in the route) the variable name should be capitalised for consistency, also fund_id and round_id should be query args like `/service/magic-links/new?fund_id={fund_id}&round_id={round_id}`

2022-05-18 16:25 UTC, ramsharma-prog commented on app/config.py
> +print(authenticator_magic_link_url)
Thanks for pointing it out 😄 
Updated!

2022-05-18 16:30 UTC, ramsharma-prog commented on manifest.yml
> +    AUTHENTICATOR_STORE_API_HOST: https://funding-service-design-authenticator-dev.london.cloudapps.digital
Yeah, I had noticed it afterwards, so had it updated but haven't pushed the changes yet. Thanks for pointing it out tho 😄

2022-05-19 10:35 UTC, harryyo approved these changes
All good, just one note about be worth having env variables follow a consistent naming pattern to avoid errors in future

2022-05-19 10:35 UTC, harryyo commented on app/config.py
> +TEST_AUTHENTICATOR_API_HOST = "authenticator_host"
As you're using AUTHENTICATOR_HOST below it would be best to just call this TEST_AUTHENTICATOR_HOST (so it's clear it's the test version of that variable

2022-05-19 10:35 UTC, harryyo commented on app/config.py
> +)
Here make the variable names AUTHENTICATOR_HOST or TEST_AUTHENTICATOR_HOST (Keeping consistent variable naming will make it less likely to make config errors down the line)

2022-05-19 10:35 UTC, harryyo commented on manifest.yml
> +    AUTHENTICATOR_API_HOST: https://funding-service-design-authenticator-dev.london.cloudapps.digital
And make this just AUTHENTICATOR_HOST

2022-05-19 10:35 UTC, harryyo commented on manifest.yml
> +    AUTHENTICATOR_API_HOST: https://funding-service-design-authenticator-test.london.cloudapps.digital
AUTHENTICATOR_HOST here too

2022-05-19 12:23 UTC, ramsharma-prog commented on app/config.py
> +TEST_AUTHENTICATOR_API_HOST = "authenticator_host"
Haha, I had it changed to AUTHENTICATOR_HOST at the beginning of reviews but your last comment was to rename it to AUTHENTICATOR_API_HOST. Will do

2022-05-19 12:23 UTC, ramsharma-prog commented on app/config.py
> +TEST_AUTHENTICATOR_API_HOST = "authenticator_host"
Haha, I had it changed to AUTHENTICATOR_HOST at the beginning of reviews but your last comment was to rename it to AUTHENTICATOR_API_HOST. Will do

2022-05-23 15:47 UTC, gio-karunakaran commented on app/discovery/forms.py
> +    search = StringField("Search fund", validators=[DataRequired()])
⛏️ do we need data to make a search or can we display all results from hitting enter from an empty search?

2022-05-23 16:03 UTC, gio-karunakaran submitted a review, later dismissed
💯 all looks great! just 1 minor comment/ query, but all fine :D

2022-05-23 17:04 UTC, ramsharma-prog commented on app/discovery/forms.py
> +    search = StringField("Search fund", validators=[DataRequired()])
Yes, we need to have an option to make a search with keywords 😄

2022-05-23 17:48 UTC, ramsharma-prog commented on app/config.py
> +)
Done!

2022-05-25 09:03 UTC, ramsharma-prog commented on manifest.yml
> +    AUTHENTICATOR_API_HOST: https://funding-service-design-authenticator-dev.london.cloudapps.digital
Update 😄

2022-05-25 09:05 UTC, ramsharma-prog commented on app/discovery/routes.py
>      if response.status_code == 200:
route removed

2022-05-25 09:35 UTC, SentientHousePlant approved these changes

2022-05-25 10:22 UTC, endamccormack approved these changes

2022-05-25 10:31 UTC, gio-karunakaran commented on app/discovery/forms.py
> +    search = StringField("Search fund", validators=[DataRequired()])
💯 fair enough! all good with me

2022-05-25 10:43 UTC, merged